<?php

namespace AppBundle\Repository;

/**
 * EtapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapaRepository extends \Doctrine\ORM\EntityRepository
{
}
